linters-settings:
  gocyclo:
    min-complexity: 45
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3

issues:
  # exclude from linting reports various type conversion code smells in the denco router.
  exclude-rules:
  - path: middleware/denco
    linters:
    - gosec
    text: G115

linters:
  enable-all: true
  disable:
    - err113 # disabled temporarily: there are just too many issues to address
    - nilerr # nilerr crashes on this repo
    - recvcheck
    - unparam
    - lll
    - gochecknoinits
    - gochecknoglobals
    - funlen
    - godox
    - gocognit
    - whitespace
    - wsl
    - wrapcheck
    - testpackage
    - nlreturn
    - errorlint
    - nestif
    - godot
    - gofumpt
    - paralleltest
    - tparallel
    - thelper
    - exhaustruct
    - varnamelen
    - gci
    - depguard
    - errchkjson
    - inamedparam
    - nonamedreturns
    - musttag
    - ireturn
    - forcetypeassert
    - cyclop
    # deprecated linters
    #- deadcode
    #- interfacer
    #- scopelint
    #- varcheck
    #- structcheck
    #- golint
    #- nosnakecase
    #- maligned
    #- goerr113
    #- ifshort
    #- gomnd
    #- exhaustivestruct
