// SPDX-FileCopyrightText: Copyright 2015-2025 go-swagger maintainers
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (c) 2014 Naoya Inada <naoina@kuune.org>
// SPDX-License-Identifier: MIT

package denco_test

// Test-only constants extracted to satisfy the goconst linter.
// They are shared across router_test.go, server_test.go and util_test.go.

const (
	testRoute0 = "testroute0"
	testRoute1 = "testroute1"
	testRoute2 = "testroute2"
	testRoute3 = "testroute3"
)

const notFoundBody = "404 page not found\n"

const (
	pathPathToRoute   = "/path/to/route"
	pathUserAlice     = "/user/alice"
	pathUserID        = "/user/:id"
	pathUserIDGroup   = "/user/:id/:group"
	pathUserIDPostCID = "/user/:id/post/:cid"
)

const (
	pathActivities                 = "/activities"
	pathActivitiesActivityID       = "/activities/:activityId"
	pathActivitiesComments         = "/activities/:activityId/comments"
	pathActivitiesPeople           = "/activities/:activityId/people/:collection"
	pathAppsTokens                 = "/applications/:client_id/tokens/:access_token"
	pathAuthorizations             = "/authorizations"
	pathAuthorizationsID           = "/authorizations/:id"
	pathCommentsCommentID          = "/comments/:commentId"
	pathEmojis                     = "/emojis"
	pathEvents                     = "/events"
	pathFeeds                      = "/feeds"
	pathGists                      = "/gists"
	pathGistsID                    = "/gists/:id"
	pathGistsIDStar                = "/gists/:id/star"
	pathGitignoreTemplate          = "/gitignore/templates/:name"
	pathGitignoreTemplates         = "/gitignore/templates"
	pathIssues                     = "/issues"
	pathLegacyIssuesSearch         = "/legacy/issues/search/:owner/:repository/:state/:keyword"
	pathLegacyReposSearch          = "/legacy/repos/search/:keyword"
	pathLegacyUserEmail            = "/legacy/user/email/:email"
	pathLegacyUserSearch           = "/legacy/user/search/:keyword"
	pathMeta                       = "/meta"
	pathNetworksEvents             = "/networks/:owner/:repo/events"
	pathNotifications              = "/notifications"
	pathNotificationThreadSub      = "/notifications/threads/:id/subscription"
	pathNotificationThreads        = "/notifications/threads/:id"
	pathOrgsEvents                 = "/orgs/:org/events"
	pathOrgsIssues                 = "/orgs/:org/issues"
	pathOrgsMember                 = "/orgs/:org/members/:user"
	pathOrgsMembers                = "/orgs/:org/members"
	pathOrgsOrg                    = "/orgs/:org"
	pathOrgsPublicMember           = "/orgs/:org/public_members/:user"
	pathOrgsPublicMembers          = "/orgs/:org/public_members"
	pathOrgsRepos                  = "/orgs/:org/repos"
	pathOrgsTeams                  = "/orgs/:org/teams"
	pathPeople                     = "/people"
	pathPeopleActivities           = "/people/:userId/activities/:collection"
	pathPeopleMoments              = "/people/:userId/moments/:collection"
	pathPeopleOpenIDConnect        = "/people/:userId/openIdConnect"
	pathPeoplePeople               = "/people/:userId/people/:collection"
	pathPeopleUserID               = "/people/:userId"
	pathRateLimit                  = "/rate_limit"
	pathRepoOwnerRepo              = "/repos/:owner/:repo"
	pathRepositories               = "/repositories"
	pathReposAssignee              = "/repos/:owner/:repo/assignees/:assignee"
	pathReposAssignees             = "/repos/:owner/:repo/assignees"
	pathReposBranch                = "/repos/:owner/:repo/branches/:branch"
	pathReposBranches              = "/repos/:owner/:repo/branches"
	pathReposCollaborator          = "/repos/:owner/:repo/collaborators/:user"
	pathReposCollaborators         = "/repos/:owner/:repo/collaborators"
	pathReposComment               = "/repos/:owner/:repo/comments/:id"
	pathReposComments              = "/repos/:owner/:repo/comments"
	pathReposCommit                = "/repos/:owner/:repo/commits/:sha"
	pathReposCommits               = "/repos/:owner/:repo/commits"
	pathReposCommitsSHAComments    = "/repos/:owner/:repo/commits/:sha/comments"
	pathReposContributors          = "/repos/:owner/:repo/contributors"
	pathReposDownload              = "/repos/:owner/:repo/downloads/:id"
	pathReposDownloads             = "/repos/:owner/:repo/downloads"
	pathReposEvents                = "/repos/:owner/:repo/events"
	pathReposForks                 = "/repos/:owner/:repo/forks"
	pathReposGitBlobs              = "/repos/:owner/:repo/git/blobs/:sha"
	pathReposGitCommits            = "/repos/:owner/:repo/git/commits/:sha"
	pathReposGitRefs               = "/repos/:owner/:repo/git/refs"
	pathReposGitTags               = "/repos/:owner/:repo/git/tags/:sha"
	pathReposGitTrees              = "/repos/:owner/:repo/git/trees/:sha"
	pathReposHook                  = "/repos/:owner/:repo/hooks/:id"
	pathReposHooks                 = "/repos/:owner/:repo/hooks"
	pathReposIssue                 = "/repos/:owner/:repo/issues/:number"
	pathReposIssueComments         = "/repos/:owner/:repo/issues/:number/comments"
	pathReposIssueEvents           = "/repos/:owner/:repo/issues/:number/events"
	pathReposIssueLabels           = "/repos/:owner/:repo/issues/:number/labels"
	pathReposIssues                = "/repos/:owner/:repo/issues"
	pathReposKey                   = "/repos/:owner/:repo/keys/:id"
	pathReposKeys                  = "/repos/:owner/:repo/keys"
	pathReposLabel                 = "/repos/:owner/:repo/labels/:name"
	pathReposLabels                = "/repos/:owner/:repo/labels"
	pathReposLanguages             = "/repos/:owner/:repo/languages"
	pathReposMilestone             = "/repos/:owner/:repo/milestones/:number"
	pathReposMilestoneLabels       = "/repos/:owner/:repo/milestones/:number/labels"
	pathReposMilestones            = "/repos/:owner/:repo/milestones"
	pathReposNotifications         = "/repos/:owner/:repo/notifications"
	pathReposPull                  = "/repos/:owner/:repo/pulls/:number"
	pathReposPullComments          = "/repos/:owner/:repo/pulls/:number/comments"
	pathReposPullCommits           = "/repos/:owner/:repo/pulls/:number/commits"
	pathReposPullFiles             = "/repos/:owner/:repo/pulls/:number/files"
	pathReposPullMerge             = "/repos/:owner/:repo/pulls/:number/merge"
	pathReposPulls                 = "/repos/:owner/:repo/pulls"
	pathReposReadme                = "/repos/:owner/:repo/readme"
	pathReposRelease               = "/repos/:owner/:repo/releases/:id"
	pathReposReleaseAssets         = "/repos/:owner/:repo/releases/:id/assets"
	pathReposReleases              = "/repos/:owner/:repo/releases"
	pathReposStargazers            = "/repos/:owner/:repo/stargazers"
	pathReposStatsCodeFrequency    = "/repos/:owner/:repo/stats/code_frequency"
	pathReposStatsCommitActivity   = "/repos/:owner/:repo/stats/commit_activity"
	pathReposStatsContributors     = "/repos/:owner/:repo/stats/contributors"
	pathReposStatsParticipation    = "/repos/:owner/:repo/stats/participation"
	pathReposStatsPunchCard        = "/repos/:owner/:repo/stats/punch_card"
	pathReposStatuses              = "/repos/:owner/:repo/statuses/:ref"
	pathReposSubscribers           = "/repos/:owner/:repo/subscribers"
	pathReposSubscription          = "/repos/:owner/:repo/subscription"
	pathReposTags                  = "/repos/:owner/:repo/tags"
	pathReposTeams                 = "/repos/:owner/:repo/teams"
	pathSearchCode                 = "/search/code"
	pathSearchIssues               = "/search/issues"
	pathSearchRepositories         = "/search/repositories"
	pathSearchUsers                = "/search/users"
	pathTeamsID                    = "/teams/:id"
	pathTeamsMember                = "/teams/:id/members/:user"
	pathTeamsMembers               = "/teams/:id/members"
	pathTeamsRepo                  = "/teams/:id/repos/:owner/:repo"
	pathTeamsRepos                 = "/teams/:id/repos"
	pathUser                       = "/user"
	pathUserEmails                 = "/user/emails"
	pathUserFollowers              = "/user/followers"
	pathUserFollowing              = "/user/following"
	pathUserFollowingUser          = "/user/following/:user"
	pathUserIssues                 = "/user/issues"
	pathUserKey                    = "/user/keys/:id"
	pathUserKeys                   = "/user/keys"
	pathUserOrgs                   = "/user/orgs"
	pathUserRepos                  = "/user/repos"
	pathUserStarred                = "/user/starred"
	pathUserStarredOwnerRepo       = "/user/starred/:owner/:repo"
	pathUserSubscriptions          = "/user/subscriptions"
	pathUserSubscriptionsOwnerRepo = "/user/subscriptions/:owner/:repo"
	pathUserTeams                  = "/user/teams"
	pathUsers                      = "/users"
	pathUsersEvents                = "/users/:user/events"
	pathUsersEventsOrgs            = "/users/:user/events/orgs/:org"
	pathUsersEventsPublic          = "/users/:user/events/public"
	pathUsersFollowers             = "/users/:user/followers"
	pathUsersFollowing             = "/users/:user/following"
	pathUsersFollowingTarget       = "/users/:user/following/:target_user"
	pathUsersGists                 = "/users/:user/gists"
	pathUsersKeys                  = "/users/:user/keys"
	pathUsersOrgs                  = "/users/:user/orgs"
	pathUsersReceivedEvents        = "/users/:user/received_events"
	pathUsersReceivedEventsPublic  = "/users/:user/received_events/public"
	pathUsersRepos                 = "/users/:user/repos"
	pathUsersStarred               = "/users/:user/starred"
	pathUsersSubscriptions         = "/users/:user/subscriptions"
	pathUsersUser                  = "/users/:user"
)

const (
	paramActivityID = "activityId"
	paramCollection = "collection"
	paramID         = "id"
	paramKeyword    = "keyword"
	paramName1      = "name1"
	paramNumber     = "number"
	paramOrg        = "org"
	paramOwner      = "owner"
	paramParam1     = "param1"
	paramParam2     = "param2"
	paramRepo       = "repo"
	paramSHA        = "sha"
	paramUser       = "user"
	paramUserID     = "userId"
	paramValue      = "value"
)

const (
	valDenco     = "denco"
	valFoo       = "foo"
	valMe        = "me"
	valNaoina    = "naoina"
	valSHA1      = "03c3bbc7f0d12268b9ca53d4fbfd8dc5ae5697b9"
	valSomething = "something"
	valTest      = "test"
	valVault     = "vault"
)
