name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@34a5baa33361844b1d2c70cd4548e3cea83529d9 # v0.2.13
    secrets: inherit
