name: Vulnerability scans

on:
  branch_protection_rule:
  push:
    branches: ["master"]
  schedule:
    - cron: "18 4 * * 3"

permissions:
  contents: read

jobs:
  scanners:
    permissions:
      contents: read
      security-events: write
    uses: go-openapi/ci-workflows/.github/workflows/scanner.yml@dd30d73a412f22d7f55aa083fba6ca3d7c44b087 # v0.2.14
    secrets: inherit
